### ISSUE TITLE
Multi-language support?

### ISSUE THREAD

**Issue by bitbasica** [PythonTurtle/PythonTurtle#141]
Thanks for the authors!
My question is that if I want to make pythonturtle more fit to other language environment like Chinese, How can I do it? Or there exists multi-language supported version?

Thanks again!

**Comment by bittner** [comment]
@cool-RR Wouldn't it be better to say, "we'd appreciate a PR or sponsorship".

Because, first this is not infeasible to do (especially since there is very little text as you point out correctly) and second it's important to make transparent that this is a total volunteers' projects.

Said that, if there'd be monthly sponsorship I'd be happy to implement multi-language support and support a community of translators.

**Comment by cool-RR** [comment]
If we introduce multi-language support, it's an architecture change that can affect all future changes and make PythonTurtle development more complicated. So it isn't just about funding setting it up and making Chinese translations, it also means that in the future, whenever we add English content, we'll have to either add corresponding Chinese content, or make a policy for dealing with content that's available in only some of the languages. It'll be worthwhile to embark on that adventure only if I know there's commitment from someone to maintain that or fund that, and that's unlikely. We don't even have a flow for creating a Windows installer, which is a sorely-needed feature.

Most volunteer projects won't let you do what you want with the architecture, even if you volunteer or give money.
